/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTrackersNewRouteImport } from './routes/_authenticated/trackers/new'
import { Route as AuthenticatedTrackersTrackerIdIndexRouteImport } from './routes/_authenticated/trackers/$trackerId/index'
import { Route as AuthenticatedTrackersTrackerIdEditRouteImport } from './routes/_authenticated/trackers/$trackerId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackersNewRoute =
  AuthenticatedTrackersNewRouteImport.update({
    id: '/trackers/new',
    path: '/trackers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackersTrackerIdIndexRoute =
  AuthenticatedTrackersTrackerIdIndexRouteImport.update({
    id: '/trackers/$trackerId/',
    path: '/trackers/$trackerId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackersTrackerIdEditRoute =
  AuthenticatedTrackersTrackerIdEditRouteImport.update({
    id: '/trackers/$trackerId/edit',
    path: '/trackers/$trackerId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trackers/new': typeof AuthenticatedTrackersNewRoute
  '/trackers/$trackerId/edit': typeof AuthenticatedTrackersTrackerIdEditRoute
  '/trackers/$trackerId/': typeof AuthenticatedTrackersTrackerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trackers/new': typeof AuthenticatedTrackersNewRoute
  '/trackers/$trackerId/edit': typeof AuthenticatedTrackersTrackerIdEditRoute
  '/trackers/$trackerId': typeof AuthenticatedTrackersTrackerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trackers/new': typeof AuthenticatedTrackersNewRoute
  '/_authenticated/trackers/$trackerId/edit': typeof AuthenticatedTrackersTrackerIdEditRoute
  '/_authenticated/trackers/$trackerId/': typeof AuthenticatedTrackersTrackerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/trackers/new'
    | '/trackers/$trackerId/edit'
    | '/trackers/$trackerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/dashboard'
    | '/settings'
    | '/trackers/new'
    | '/trackers/$trackerId/edit'
    | '/trackers/$trackerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/trackers/new'
    | '/_authenticated/trackers/$trackerId/edit'
    | '/_authenticated/trackers/$trackerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackers/new': {
      id: '/_authenticated/trackers/new'
      path: '/trackers/new'
      fullPath: '/trackers/new'
      preLoaderRoute: typeof AuthenticatedTrackersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackers/$trackerId/': {
      id: '/_authenticated/trackers/$trackerId/'
      path: '/trackers/$trackerId'
      fullPath: '/trackers/$trackerId/'
      preLoaderRoute: typeof AuthenticatedTrackersTrackerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trackers/$trackerId/edit': {
      id: '/_authenticated/trackers/$trackerId/edit'
      path: '/trackers/$trackerId/edit'
      fullPath: '/trackers/$trackerId/edit'
      preLoaderRoute: typeof AuthenticatedTrackersTrackerIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrackersNewRoute: typeof AuthenticatedTrackersNewRoute
  AuthenticatedTrackersTrackerIdEditRoute: typeof AuthenticatedTrackersTrackerIdEditRoute
  AuthenticatedTrackersTrackerIdIndexRoute: typeof AuthenticatedTrackersTrackerIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrackersNewRoute: AuthenticatedTrackersNewRoute,
  AuthenticatedTrackersTrackerIdEditRoute:
    AuthenticatedTrackersTrackerIdEditRoute,
  AuthenticatedTrackersTrackerIdIndexRoute:
    AuthenticatedTrackersTrackerIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
