/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackersNewRouteImport } from './routes/trackers/new'
import { Route as TrackersTrackerIdIndexRouteImport } from './routes/trackers/$trackerId/index'
import { Route as TrackersTrackerIdEditRouteImport } from './routes/trackers/$trackerId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersNewRoute = TrackersNewRouteImport.update({
  id: '/trackers/new',
  path: '/trackers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersTrackerIdIndexRoute = TrackersTrackerIdIndexRouteImport.update({
  id: '/trackers/$trackerId/',
  path: '/trackers/$trackerId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersTrackerIdEditRoute = TrackersTrackerIdEditRouteImport.update({
  id: '/trackers/$trackerId/edit',
  path: '/trackers/$trackerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/trackers/new': typeof TrackersNewRoute
  '/trackers/$trackerId/edit': typeof TrackersTrackerIdEditRoute
  '/trackers/$trackerId/': typeof TrackersTrackerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/trackers/new': typeof TrackersNewRoute
  '/trackers/$trackerId/edit': typeof TrackersTrackerIdEditRoute
  '/trackers/$trackerId': typeof TrackersTrackerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/trackers/new': typeof TrackersNewRoute
  '/trackers/$trackerId/edit': typeof TrackersTrackerIdEditRoute
  '/trackers/$trackerId/': typeof TrackersTrackerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings'
    | '/trackers/new'
    | '/trackers/$trackerId/edit'
    | '/trackers/$trackerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings'
    | '/trackers/new'
    | '/trackers/$trackerId/edit'
    | '/trackers/$trackerId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings'
    | '/trackers/new'
    | '/trackers/$trackerId/edit'
    | '/trackers/$trackerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TrackersNewRoute: typeof TrackersNewRoute
  TrackersTrackerIdEditRoute: typeof TrackersTrackerIdEditRoute
  TrackersTrackerIdIndexRoute: typeof TrackersTrackerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/new': {
      id: '/trackers/new'
      path: '/trackers/new'
      fullPath: '/trackers/new'
      preLoaderRoute: typeof TrackersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/$trackerId/': {
      id: '/trackers/$trackerId/'
      path: '/trackers/$trackerId'
      fullPath: '/trackers/$trackerId/'
      preLoaderRoute: typeof TrackersTrackerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/$trackerId/edit': {
      id: '/trackers/$trackerId/edit'
      path: '/trackers/$trackerId/edit'
      fullPath: '/trackers/$trackerId/edit'
      preLoaderRoute: typeof TrackersTrackerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TrackersNewRoute: TrackersNewRoute,
  TrackersTrackerIdEditRoute: TrackersTrackerIdEditRoute,
  TrackersTrackerIdIndexRoute: TrackersTrackerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
